global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8080']
    metrics_path: '/metrics'

  - job_name: 'properties-service'
    static_configs:
      - targets: ['properties-service:8080']
    metrics_path: '/metrics'

  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['ingestion-service:8080']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8080']
    metrics_path: '/metrics'
